- name: Install zabbix repositories
  yum:
    name: 'https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm'
    state: present
- name: Install/update package zabbix-agent to latest version
  yum:
    name: 'zabbix-agent'
    state: latest
    update_cache: yes
- name: Generate configuration file for zabbix-agent
  template:
    src: 'zabbix_agentd.conf.j2'
    dest: '/etc/zabbix/zabbix_agentd.conf'
  notify: restart zabbix-agent service
- name: Enable and start zabbix-agent service
  service:
    name: 'zabbix-agent'
    state: started
    enabled: True
- name: Open port 10050/tcp on firewalld
  firewalld:
    port: '10050/tcp'
    permanent: True
    immediate: True
    state: enabled
